spring:
  application:
    name: book-service-dev

server:
  port: 8090

custom:
  book-service-header-name: X-DEV-BookID

logging:
  level:
    cz.gopas.book.controller.BookControllerV1: trace
    root: info
