spring:
  application:
    name: book-service
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://192.168.56.101/book_store
    username: postgres
    password: linux
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 7001


custom:
  book-service-header-name: X-BookID
  storage:
      type: db

logging:
  level:
    root: warn

# Actuator (monitoring) config
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans